### ISSUE TITLE
ingame doesn't recover from an API error

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/ingame#7]
When an error related to the API occurred, ingame didn't try again and just completely stopped working. `/poll` didn't work either.

```
[20:12:10 ERROR]: TaskChain Exception on rip.bolt.ingame.ranked.MatchSearch$$Lambda$687/0x00000000b92959b0: Map null wasn't found in PGM's map library. Make sure it is listed in /maps and  │
│ [20:12:10 ERROR]: Current Action Index was: 3                                                                                                                                                │
│ [20:12:10 WARN]: java.lang.IllegalArgumentException: Map null wasn't found in PGM's map library. Make sure it is listed in /maps and restart the server!                                     │
│ [20:12:10 WARN]:     at dev.pgm.events.format.rounds.single.SingleRound.<init>(SingleRound.java:39)                                                                                          │
│ [20:12:10 WARN]:     at rip.bolt.ingame.ranked.RankedManager.setupMatch(RankedManager.java:91)                                                                                               │
│ [20:12:10 WARN]:     at rip.bolt.ingame.ranked.RankedManager$$Lambda$597/0x00000000b91e8360.accept(Unknown Source)                                                                           │
│ [20:12:10 WARN]:     at rip.bolt.ingame.ranked.MatchSearch$$Lambda$687/0x00000000b92959b0.runLast(Unknown Source)                                                                            │
│ [20:12:10 WARN]:     at rip.bolt.ingame.taskchain.TaskChainTasks$LastTask.run(TaskChainTasks.java:70)                                                                                        │
│ [20:12:10 WARN]:     at rip.bolt.ingame.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)                                                                                              │
│ [20:12:10 WARN]:     at rip.bolt.ingame.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)                                                                                       │
│ [20:12:10 WARN]:     at rip.bolt.ingame.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1194)                                                                                          │
│ [20:12:10 WARN]:     at rip.bolt.ingame.taskchain.TaskChain$$Lambda$691/0x00000000a40a03c0.run(Unknown Source)                                                                               │
│ [20:12:10 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)                                                                                            │
│ [20:12:10 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412)                                                                 │
│ [20:12:10 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:893)                                                                                             │
│ [20:12:10 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823)                                                                                             │
│ [20:12:10 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724)                                                                                           │
│ [20:12:10 WARN]:     at java.lang.Thread.run(Unknown Source)
´´´

**Comment by Pugzy** [comment]
Should be fixed by admin commands in https://github.com/bolt-rip/ingame/commit/bf6b9fd073b9cbed4f6a952f12d323f78f99dd6e and https://github.com/bolt-rip/ingame/commit/f5e3fb53f9c2eaf7f9ef7c219e222e9595bbf0b5 with extra validity checks.
